#这些配置会被保留，如果和下面的重复则会被覆盖
spring:
  profiles:
    active: dev
  application:
    name: spring yaml example

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.112.101:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

#配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    ##  预防报错： Invalid bean definition with name 'webSecurityExpressionHandler'
    ##
  main:
    allow-bean-definition-overriding: true
#debug
logging:
  level:
    root: debug
---
#当环境为dev时采用该配置
spring:
  profiles: dev
server:
  tomcat:
    uri-encoding: utf-8
  port: 9600
---
#当环境为prod时采用该配置
spring:
  profiles: prod
server:
  tomcat:
    uri-encoding: utf-8
  port: 9600


